site_name: AI SDLC Playbook
site_url: https://kevinlin.github.io/ai-sdlc-playbook
repo_url: https://github.com/kevinlin/ai-sdlc-playbook
edit_uri: edit/main/docs/
site_author: Kevin Lin <kevin.lin@zuhlke.com>
use_directory_urls: true
theme:
  name: material
  locale: en
  logo: img/ai-sdlc-icon.svg
  favicon: img/favicon.svg
  palette:
    primary: custom
  font:
    text: Luto
  features:
    - content.action.edit
    - content.code.copy
extra_css:
- stylesheets/extra.css
plugins:
  - search
  - awesome-nav
  - mermaid2
markdown_extensions:
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - attr_list
watch:
  - docs
extra:
  generator: false
copyright: Copyright &copy; 2025 Zühlke Technology Group AG
