title: Feature-based development
nav:
  - README.md
  - 01-getting-started.md
  - 02-requirement-specification.md
  - 03-technical-design.md
  - 04-development.md
  - 041-testing.md
  - 042-refactoring.md
  - 05-change-management.md
  - 07-documentation.md